version: "3.1"
services:
  freegames:
    build: .
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    depends_on:
      - "db"
  db:
    image: "mongo"
    restart: always
    ports:
      - "27017:27017"
