version: "3.1"
services:
  freegames:
    build: .
    restart: always
    links:
      - "db:database"
    environment:
      - "DATABASE_URL=mongodb://db:27017"
    depends_on:
      - "db"
  db:
    image: "mongo"
    restart: always
    ports:
      - "27017:27017"
