// Code generated by mockery v2.9.4. DO NOT EDIT.

package mockplatform

import (
	freegames "github.com/arkiant/freegames/internal"
	mock "github.com/stretchr/testify/mock"
)

// Platform is an autogenerated mock type for the Platform type
type Platform struct {
	mock.Mock
}

// GetName provides a mock function with given fields:
func (_m *Platform) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Run provides a mock function with given fields:
func (_m *Platform) Run() (freegames.FreeGames, error) {
	ret := _m.Called()

	var r0 freegames.FreeGames
	if rf, ok := ret.Get(0).(func() freegames.FreeGames); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(freegames.FreeGames)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
